### ISSUE TITLE
CLI requires Java 11

### ISSUE THREAD

**Issue by lgblaumeiser** [lgblaumeiser/ProjectTimeManager#100]
WA3Z007H:~ gel2fr$ ptm ab -a 13 -s 08:00 -c "Offene Punkte, Projektsetup, Planung"
Add new booking ...
Exception in thread "main" java.lang.NoSuchMethodError: java.util.Optional.ifPresentOrElse(Ljava/util/function/Consumer;Ljava/lang/Runnable;)V
    at de.lgblaumeiser.ptm.cli.engine.handler.AddBooking.handleCommand(AddBooking.java:56)
    at de.lgblaumeiser.ptm.cli.CLI.runCommand(CLI.java:27)
    at de.lgblaumeiser.ptm.cli.ProjectTimeManager.main(ProjectTimeManager.java:17)
WA3Z007H:~ gel2fr$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by lgblaumeiser** [comment]
Method isPresentOrElse came with Java 9, solution, require JDK 11 for CLI, no support for Java 8 anymore
